# Generated by Django 5.0.4 on 2024-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="telefon",
            field=models.IntegerField(),
        ),
    ]
