# Generated by Django 5.0.4 on 2024-05-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_gymnast_grupp_alter_gymnast_user_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymnast",
            name="efternamn",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="gymnast",
            name="förnamn",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="gymnast",
            name="personnummer",
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name="profile",
            name="adress",
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name="profile",
            name="efternamn",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="förnamn",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="telefon",
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
